config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: "pages#home"
  resources :dogs do
    resources :bookings, only: %i[new create]
  end
  # list of all user bookings
  get '/my-bookings', to: 'bookings#index', as: 'mycart'

  # list a booking
  get '/my-bookings/:id', to: 'bookings#show', as: 'mybooking'

  # list all dogs(owner)
  get '/my-dogs', to: 'dogs#mydogs', as: 'mydogs'

  # list a dog(owner)
  get '/my-dogs/:id', to: 'dogs#show', as: 'mydog'

  # remove your dog from website
  delete '/my-dogs/:id', to: "dogs#destroy", as: 'removedog'

  # update dog posting
  patch '/my-dogs/:id', to: 'dogs#update'

  #remove your booking
  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :dog
  belongs_to :user

  validates :startdate, :enddate, :user_id, :dog_id, presence: true
  validates :startdate, comparison: { less_than: :enddate }
  validate :not_the_same_date

  private

  def not_the_same_date
    if enddate == startdate
      errors.add(:enddate, "must be after the start date")
    end
  end
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :name, presence: true, length: { in: 3..50 }, uniqueness: true
  validates :breed, length: { in: 3..50 }
  validates :price, numericality: { only_integer: true }
  validates :description, presence: true
  validates :skills, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dogs
  has_many :bookings, through: :dogs
  has_many :rentals, class_name: 'Booking'

  geocoded_by :address
  after_validation :geocode, if:
  :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:address])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dog, only: %i[create new]
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = current_user.bookings
    @mydogs = current_user.dogs
    @rentals = []
    @mydogs.each do |dog|
      @rentals.append(dog.bookings)
    end
    @bookings = Booking.all
    counter = @bookings.count
    $cart_counter = counter
  end

  def show
    @dog = Dog.find(@booking.dog_id)
  end

  def new
    @booking = Booking.new
    @booking.dog_id = @dog
  end


  def create
    @booking = Booking.new(booking_params)
    @booking.dog = @dog
    @booking.user = current_user
    if @booking.save
      redirect_to mybooking_path(@booking), notice: 'booking was successfully created'
    else
      redirect_to dog_bookings_path
    end
  end


  def edit
  end

  def update
    @booking.update(params[booking_params])
    redirect_to my_booking_path(@booking)
  end

  def destroy
    @booking.destroy
    redirect_to dogs_path, status: :see_other
  end

  private

  def set_dog
    @dog = Dog.find(params[:dog_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:startdate, :enddate)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  before_action :set_dog, only: %i[show update destroy edit]

  def index
    @dogs = Dog.all
  end

  def show
    @dog = set_dog
    @markers = [
      {
        lat: @dog.user.latitude,
        lng: @dog.user.longitude,
        image_url: helpers.asset_url("dog.jpg")
      }
    ]
  end

  def new
    @dog = Dog.new
  end

  def create
    @mydog = Dog.new(dog_params)
    @mydog.user = current_user
    if @mydog.save!
      redirect_to mydogs_path, notice: 'dog was successfully created'
    else
      redirect_to new_dog_path, notice: 'Your dogs details were not correct, try again'
    end
  end

  def mydogs
    @mydogs = Dog.all
  end

  def edit; end

  def update
    if @dog.update(dog_params)
      redirect_to mydog_path, notice: 'dog was successfully updated'
    else
      redirect_to mydogs_path, notice: 'dog was not created please try again'
    end
  end

  def destroy
    set_dog
    rufus = @dog.name
    @dog.destroy
    redirect_to mydogs_path, status: :see_other, notice: "You removed #{rufus} from Whoof"
  end

  private

  def set_dog
    @dog = Dog.find(params[:id])
  end

  def dog_params
    params.require(:dog).permit(:name, :breed, :skills, :description, :photo, :price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @dogs = Dog.all.sample(6)
    @dog_group1 = @dogs.first(3)
    @dog_group2 = @dogs.last(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_shoppingcart.html.erb
<div class="d-flex justify-content-between">
  <div class="col-md-4 order-md-2 px-4 pt-3"style="position: sticky;">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-muted">Your cart</span>
      <span class="badge badge-secondary badge-pill">3</span>
    </h4>
    <ul class="list-group mb-3 sticky-top">
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0"><%= @dog.name%></h6>
        </div>
      </li>
      <li class="list-group-item d-flex justify-content-between">
        <span class="text-muted">
          <h6>Your booking: <strong><%= @booking.startdate%> - <%= @booking.enddate %></strong></h6>
        </span>
      </li>
      <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>$<%= @dog.price%></strong>
      </li>
    </ul>
  </div>
  <div class="col-md-7 px-4 pt-3 pb-4 mb-2">
    <h4 class="mb-3">Billing address</h4>
    <form class="needs-validation" novalidate="">
      <div class="row">
        <div class="col-md-6 mb-3">
          <label for="firstName">First name</label>
          <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
          <div class="invalid-feedback"> Valid first name is required. </div>
        </div>
        <div class="col-md-6 mb-3">
          <label for="lastName">Last name</label>
          <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
          <div class="invalid-feedback"> Valid last name is required. </div>
        </div>
      </div>
      <div class="mb-3">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" placeholder="you@example.com">
        <div class="invalid-feedback"> Please enter a valid email address for shipping updates. </div>
      </div>
      <div class="mb-3">
        <label for="address">Address</label>
        <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
        <div class="invalid-feedback"> Please enter your shipping address. </div>
      </div>
      <div class="row">
        <div class="col-md-5 mb-3">
          <label for="country">Country</label>
          <select class="custom-select d-block w-100" id="country" required="">
            <option value="">Choose...</option>
            <option>Canada</option>
            <option>United States</option>
          </select>
          <div class="invalid-feedback"> Please select a valid country. </div>
        </div>
        <div class="col-md-4 mb-3">
          <label for="state">State</label>
          <select class="custom-select d-block w-100" id="state" required="">
            <option value="">Choose...</option>
            <option>Quebec</option>
            <option>California</option>
          </select>
          <div class="invalid-feedback"> Please provide a valid state. </div>
        </div>
        <div class="col-md-3 mb-3">
          <label for="zip">Zip</label>
          <input type="text" class="form-control" id="zip" placeholder="" required="">
          <div class="invalid-feedback"> Zip code required. </div>
        </div>
      </div>
      <hr class="mb-4">
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="same-address">
        <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
      </div>
      <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="save-info">
        <label class="custom-control-label" for="save-info">Save this information for next time</label>
      </div>
      <hr class="mb-4">
      <h4 class="mb-3">Payment
        <i class="fa-brands fa-cc-visa"></i>
        <i class="fa-brands fa-cc-mastercard"></i>
        <i class="fa-brands fa-cc-amex"></i>
      </h4>
      <div class="d-block my-3">
        <div class="custom-control custom-radio">
            <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked="" required="">
            <label class="custom-control-label" for="credit">Credit card</label>
        </div>
        <div class="custom-control custom-radio">
            <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required="">
            <label class="custom-control-label" for="debit">Debit card</label>
        </div>
        <div class="custom-control custom-radio">
            <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required="">
            <label class="custom-control-label" for="paypal">PayPal</label>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 mb-3">
            <label for="cc-name">Name on card</label>
            <input type="text" class="form-control" id="cc-name" placeholder="" required="">
            <small class="text-muted">Full name as displayed on card</small>
            <div class="invalid-feedback"> Name on card is required </div>
        </div>
        <div class="col-md-6 mb-3">
            <label for="cc-number">Credit card number</label>
            <input type="text" class="form-control" id="cc-number" placeholder="" required="">
            <div class="invalid-feedback"> Credit card number is required </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3 mb-3">
          <label for="cc-expiration">Expiration</label>
          <input type="text" class="form-control" id="cc-expiration" placeholder="" required="">
          <div class="invalid-feedback"> Expiration date required </div>
        </div>
        <div class="col-md-3 mb-3">
          <label for="cc-cvv">CVV</label>
          <input type="text" class="form-control" id="cc-cvv" placeholder="" required="">
          <div class="invalid-feedback"> Security code required </div>
        </div>
      </div>
      <hr class="mb-4">
      <button class="btn btn-outline-success" type="submit">Continue</button>
      <%= link_to 'Cancel',booking_path(@booking), method: :delete, class: 'btn btn-outline-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel #{@dog.name}? from your booking ?" } %>
    </form>
  </div>
</div>

app/views/bookings/index.html.erb
<div class = "container pb-4 pt-4 ">
  <% @bookings.each do |booking| %>
    <span>
      <div class = 'd-flex justify-content-between'>
        <div>
          <p>
            <% @dog = Dog.find(booking.dog_id) %>
            <%= cl_image_tag @dog.photo.key, height: 180, width: 200, crop: :fit %>
          </p>
        </div>
        <div>
          <p><%= booking.startdate %> -> <%= booking.enddate %>
          </p>
          <%= @dog.name %>
        </div>
      </div>
    </span>
    <div class="card-link" style="display: flex;flex-direction: column;">
      <%= link_to "See more", mybooking_path(booking), class: 'btn btn-flat' %>
    </div>
    <hr class="dropdown-divider">
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow text-center">
        <h3>Booking for:
          <%= @dog.name %>
        </h3>
        <%= simple_form_for [@dog, @booking] do |f| %>
          <div class="col">
            <div class="d-flex justify-content-between">
              <div class="container">
                <%= f.input  :startdate, placeholder: '1/1/2021', :label =>'Start Date' %>
              </div>
              <div class="container">
                <%= f.input  :enddate, placeholder: '1/1/2021', :label =>'End Date' %>
              </div>
            </div>
          </div>
          <%= f.submit :label =>"Reserve", class: "btn btn-outline-success d-flex w-100" %>
          <%= link_to "Back", dog_path(@dog), class: "btn btn-outline-danger mt-2 w-100"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/shoppingcart.html.erb
<div>
  <%= link_to "Checkout", checkout_path, class: 'btn btn-outline-success' %>
</div>
</p>
  <%=@dog.price %>
<p>

app/views/bookings/show.html.erb
<div class="container p-4">
  <h1 class = "text-center">Your Current Booking</h1>
  <div class="card-trip p-4">
    <%= cl_image_tag @dog.photo.key, height: 180, width: 200, crop: :fit %>
  </div>
  <div>
    <%= render 'shoppingcart', booking: @booking %>
  </div>
</div>

app/views/dogs/_form.html.erb
<h2 class = 'text-center'>Post your Dog</h2>
<%= simple_form_for dog do |f| %>
  <%= f.input :name, placeholder: 'Morty' %>
  <%= f.input :breed, placeholder: 'Corgi' %>
  <%= f.input :skills, placeholder: 'driving your car' %>
  <%= f.input :description, placeholder: 'Corgi that really cool' %>
  <%= f.input :photo, as: :file, direct_upload: true %>
  <%= f.input :price, placeholder: '100 pesos',:collection => 20..150 %>
  <div class="d-flex justify-content-between">
    <div>
      <%= f.submit class: 'btn btn-outline-success' %>
    </div>
    <div>
      <%= link_to "Cancel", mydogs_url, class: 'btn btn-outline-danger' %>
    </div>
  </div>
<% end %>

app/views/dogs/_info_window.html.erb
  <h2><%= @dog.user.address %></h2>

app/views/dogs/edit.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <div class="column">
    <div class="form-center">
      <div class="bg-white rounded p-3 shadow">
        <h1> What would you like change about: <%= @dog.name %> ? </h1>
        <%= simple_form_for @dog do |f| %>
          <%= f.input :name %>
          <%= f.input :breed %>
          <%= f.input :photo, as: :file, direct_upload: true %>
          <%= f.input :skills, placeholder: 'driving your car' %>
          <%= f.submit class: 'btn btn-outline-success' %>
          <%= link_to 'Back',mydogs_url, class: 'btn btn-outline-danger' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dogs/index.html.erb
<div class = 'container pb-4 pt-4'>
  <div class="row no-gutters">
    <% @dogs.each do |doggo|  %>
      <div class= 'col-md-6 pb-3'>
        <div class="card-category">
          <% if doggo.photo.present? %>
            <%= cl_image_tag doggo.photo.key, height: 180, width: 200, crop: :fit %>
            <div class="card-body">
              <div class="card-title">
                <h5><%= doggo.name %></h5>
              </div>
              <div class="card-text">
                <p>Breed: <%= doggo.breed %></p>
                <p>Location: <%= doggo.user.address %></p>
                <p>Price: $<%= doggo.price %></p>
              </div>
              <div class="card-link">
                <%= link_to 'Check me out',dog_path(doggo), class: 'btn btn-outline-success' %>
              </div>
            </div>
          <%else%>
            <div class="card-body">
              <div class="card-title">
                <h5><%= doggo.name %></h5>
              </div>
              <div class="card-text">
                <p>Breed: <%= doggo.breed %></p>
                <p>location: <%= doggo.user.address %></p>
                <p>price: $<%= doggo.price %></p>
              </div>
              <div class = 'card-link'>
                <%= link_to 'Check me out',dog_path(doggo), class: 'btn btn-outline-success' %>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dogs/mydogs.html.erb
<div class="content">
  <div class="banner"style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445);">
  </div>
</div>
<h3 class = 'text-center'>Your Current Doggo Rentals</h3>

<div class = "container pb-4 pt-4">
  <div class = "row no-gutters">
    <% @mydogs.each do |mydog|  %>
      <div class="col-6 pb-3 px-5">
        <div class="d-flex justify-content-between">
          <% if mydog.photo.present? %>
            <div class = 'col'>
              <div class = 'mydog-photo-card'>
                <%= cl_image_tag mydog.photo.key, width: 252 , height:170, crop: :fill %>
              </div>
              <p>
                Name:<%=mydog.name %>
                <div>
                  Breed:<%=mydog.breed%>
                </div>
              </p>
              <div>
                Price:$<%=mydog.price%>
              </div>
              <div>
                <%= link_to 'Update dog',edit_dog_path(mydog), class: 'btn btn-outline-success' %>
                <%= link_to 'Remove dog',removedog_path(mydog.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{mydog.name} from your Rentals?"}, class: 'btn btn-outline-danger' %>
              </div>
            </div>
          <%else%>
            <div class = 'card-body'>
              <div class = "mydog-upload-title text-center">
                <h5><strong>Please upload photo</strong> </h5>
              </div>

                <p>
                  Name:<%=mydog.name %>
                  <div>
                    Breed:<%=mydog.breed%>
                  </div>
                </p>
                <div>
                  Price:$<%=mydog.price%>
                </div>

            </div>
          <%end%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dogs/new.html.erb
<div class="position-relative">
  <div class="position-absolute top-0 start-50 translate-middle-x">
    <div class= 'container mt-2'>
      <div class = 'row'>
        <%= render 'form', dog: @dog %>
      </div>
    </div>
  </div>
</div>

app/views/dogs/show.html.erb
<style>
  .marker {
  display: block;
  border: none;
  border-radius: 50%;
  padding: 0;
  }
</style>
<div class = 'map-dogs' data-controller="map"
  id='map'
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  data-map-markers-value="<%= @markers.to_json %>"
  >
</div>

<div class="container py-3">
  <div class = "cards">
    <div class="card">
      <div class = "card-body">
        <strong><%= @dog.name %> </strong>
        <% if @dog.photo.present? %>
        <div class="card-text">
          <%= cl_image_tag @dog.photo.key, height: 200, width: 100, crop: :fit %>
          <p class="card-text"> <strong> Name: </strong><%=@dog.name%></p>
          <p class="card-text"> <strong> Breed: </strong> <%=@dog.breed%></p>
          <p class="card-text"> <strong> Price:$ </strong><%=@dog.price%></p>
          <p class="card-text"> <strong> Description: </strong><%=@dog.description%></p>
          <p class="card-text"> <strong> Address:</strong> <%= @dog.user.address %>
        </div>
        <%else%>
        <div class="card-text">
          <p class="card-text"> <strong> Name: </strong><%=@dog.name%></p>
          <p class="card-text"> <strong> Breed: </strong> <%=@dog.breed%></p>
          <p class="card-text"> <strong> Price:$ </strong><%=@dog.price%></p>
          <p class="card-text"> <strong> Description: </strong><%=@dog.description%></p>
        </div>
        <%end%>
        <%= link_to 'Add a booking',new_dog_booking_path(@dog), class: 'btn btn-outline-success' %>
        <%= link_to 'Back',dogs_path, class: 'btn btn-outline-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
    <div id="page-container">
      <div id="content-wrap">
        <%= render 'shared/navbar' %>
        <%= render "shared/flashes" %>
        <%= yield %>
        <%= render 'shared/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="d-flex justify-content-between">
  <div class= 'container'>
    <h1 style="position:relative;top: 170px;">Welcome to WHOOF your one-stop shop for cuddly vibes
      <div class = 'mt-4'>
        <%= link_to "See All",dogs_url, class: "btn btn-outline-success w-100"%>
      </div>
    </h1>
  </div>
  <div class = 'container'>
    <%= image_tag("https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg?_=42445",width:'100%',height: '450px',position:'sticky') %>
  </div>
</div>

<div class = "pb-4">
  <h2 class = 'text-center pt-2'>
    The most popular dogs this week
  </h2>
</div>

<div class="landing-page-carousel">
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%# card group 1 iteration %>
        <div class="row no-gutters">
          <% @dog_group1.each do |dog1|  %>
            <div class="col-lg-4 pb-3">
              <%= link_to dog_path(dog1) do %>
                <div class = 'card-category'>
                  <% if dog1.photo.present? %>
                    <div class = "img-fluid rounded-start">
                      <%= cl_image_tag dog1.photo.key, height: 150, width: 150, crop: :fill %>
                    </div>
                    <div class = 'text-muted'>
                      <p class="card-text text-right"><strong><%= dog1.name %></strong></p>
                      <p class="card-text text-right">Price: $<%= dog1.price %></p>
                      <p class="card-text text-right">Breed:<%= dog1.breed %></p>
                    </div>
                  <%else%>
                    <div class="card-body">
                      <p class="card-text text-right"><strong><%= dog1.name %></strong></p>
                      <p class="card-text text-right">Price: $<%= dog1.price %></p>
                      <p class="card-text text-right">Breed:<%= dog1.breed %></p>
                    </div>
                  <%end%>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="carousel-item">
        <%# card group 2 iteration %>
        <div class="row no-gutters">
          <% @dog_group2.each do |dog2|  %>
            <div class="col-md-4 pb-3">
              <%= link_to dog_path(dog2) do %>
                <div class="card-category">
                  <% if dog2.photo.present? %>
                    <div class = "img-fluid rounded-start">
                      <%= cl_image_tag dog2.photo.key, height: 150, width: 150, crop: :fill %>
                    </div>
                    <div class = 'text-muted'>
                      <p class="card-text text-right"><strong><%= dog2.name %></strong></p>
                      <p class="card-text text-right">Price: $<%= dog2.price %></p>
                      <p class="card-text text-right">Breed:<%= dog2.breed %></p>
                    </div>
                  <%else%>
                    <div class="card-body">
                      <p class="card-text text-right"><strong><%= dog2.name %></strong></p>
                      <p class="card-text text-right">Price: $<%= dog2.price %></p>
                      <p class="card-text text-right">Breed:<%= dog2.breed %></p>
                    </div>
                  <%end%>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <button class="carousel-control-prev" style= 'max-width:50px;' type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" style= 'max-width:50px;' type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash alert alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="flash alert alert-dismissible fade show" role="alert">
    <span><%= alert %></span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer"id="footer-info">
  <div class="footer-copyright">
    <strong>WHOOF</strong>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to 'WHOOF', root_path, class: 'navbar-brand'%>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <div class = 'back-btn'>
          <%= link_to :back do %>
            <i class="fa-solid fa-chevron-left" style = "color:black;position: relative;right: 53px;"></i>
          <% end %>
        </div>
        <div>
          <%= link_to mycart_path do %>
            <i class="fa-solid fa-cart-shopping" style = "color:black;position: relative;right: 22px;">
              <span class="badge badge-danger" style="position: relative;right: 5px;top: -3px;color: #221f1f;">
                <%= $cart_counter %>
              </span>
            </i>
          <% end %>
        </div>
        <%= image_tag "https://img.icons8.com/ios/50/null/user-male-circle.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "Rent a dog", dogs_path, class: "dropdown-item" %>
          <%= link_to "Shopping cart", mycart_path, class: "dropdown-item"%>
          <hr class="dropdown-divider">
          <%= link_to "My Dogs", mydogs_path, class: "dropdown-item"%>
          <%= link_to "Rent Out Your Dog",new_dog_url, class: "dropdown-item" %>
          <hr class="dropdown-divider">
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
            class: "dropdown-item" %>
        </div>
      <% else %>
        <div class="nav-item" >
          <%= link_to "Login",new_user_session_path, class: "nav-link" %>
        </div>
      <%end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% @users.each do |user| %>
  <%= user.email %><br/>
<% end %>